// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadAndInstallAntiDetect():Promise<void>;

export function EnsureAntiDetectRunning():Promise<void>;

export function GetAntiDetectDestPath(arg1:{[key: string]: any}):Promise<string>;

export function GetAntiDetectDownloadURL(arg1:{[key: string]: any}):Promise<string>;

export function IsAntiDetectInstalled():Promise<boolean>;

export function IsAntiDetectRunning():Promise<boolean>;

export function ReadConfig(arg1:string):Promise<{[key: string]: any}>;

export function RunAntiDetect():Promise<void>;
