// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAndRunAntiDetect():Promise<void>;

export function DownloadAndInstallAntiDetect():Promise<void>;

export function EnsureAntiDetectRunning():Promise<void>;

export function GetInstallationProgress():Promise<number>;

export function IsAntiDetectInstalled():Promise<boolean>;

export function RunAntiDetect():Promise<void>;
