// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {browser} from '../models';

export function AddProfile(arg1:browser.CreateProfileRequest):Promise<{[key: string]: any}>;

export function FetchProfileInfo(arg1:string):Promise<browser.ProfileInfoResponse>;

export function FetchProfiles():Promise<browser.ProfileResponse>;

export function LaunchProfile(arg1:string):Promise<{[key: string]: any}>;

export function ModifyProfile(arg1:string,arg2:browser.CreateProfileRequest):Promise<{[key: string]: any}>;

export function RemoveProfile(arg1:string):Promise<{[key: string]: any}>;

export function TerminateProfile(arg1:string):Promise<{[key: string]: any}>;
