// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProfile(arg1) {
  return window['go']['browser']['BrowserManager']['AddProfile'](arg1);
}

export function FetchProfiles() {
  return window['go']['browser']['BrowserManager']['FetchProfiles']();
}

export function LaunchProfile(arg1) {
  return window['go']['browser']['BrowserManager']['LaunchProfile'](arg1);
}

export function ModifyProfile(arg1, arg2) {
  return window['go']['browser']['BrowserManager']['ModifyProfile'](arg1, arg2);
}

export function RemoveProfile(arg1) {
  return window['go']['browser']['BrowserManager']['RemoveProfile'](arg1);
}

export function TerminateProfile(arg1) {
  return window['go']['browser']['BrowserManager']['TerminateProfile'](arg1);
}
