// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {vm} from '../models';

export function CheckVMWareStatus():Promise<vm.VMWareStatus>;
