// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadAndInstallVMWare():Promise<void>;

export function GetInstallationProgress():Promise<number>;
