// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadAndInstallVMWare() {
  return window['go']['vm']['VMD']['DownloadAndInstallVMWare']();
}

export function GetInstallationProgress() {
  return window['go']['vm']['VMD']['GetInstallationProgress']();
}
