// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';

export function DeleteEmail(arg1:string):Promise<void>;

export function GetEmail(arg1:string):Promise<db.GmailAccount>;

export function ListEmails():Promise<Array<db.GmailAccount>>;

export function SaveEmail(arg1:db.GmailAccount):Promise<void>;
