// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteEmail(arg1) {
  return window['go']['db']['EmailDB']['DeleteEmail'](arg1);
}

export function GetEmail(arg1) {
  return window['go']['db']['EmailDB']['GetEmail'](arg1);
}

export function ListEmails() {
  return window['go']['db']['EmailDB']['ListEmails']();
}

export function SaveEmail(arg1) {
  return window['go']['db']['EmailDB']['SaveEmail'](arg1);
}
