// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckVMWareStatus() {
  return window['go']['main']['App']['CheckVMWareStatus']();
}

export function DownloadAndInstallVMWare() {
  return window['go']['main']['App']['DownloadAndInstallVMWare']();
}

export function GetInstallationProgress() {
  return window['go']['main']['App']['GetInstallationProgress']();
}
