// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckVMWareStatus():Promise<main.VMWareStatus>;

export function DownloadAndInstallVMWare():Promise<void>;

export function GetInstallationProgress():Promise<number>;
